### ISSUE TITLE
Tech-Profile-Download-Failure while running bbsim with voltha 1.x

### ISSUE THREAD

**Issue by siddiqui-io** [opencord/voltha-bbsim#3]
While running the bbsim with voltha1.x, I am getting tech-profile-config-download-failure-retrying status in voltha-cli. 

How I ran it: 
1. Started bbsim container using docker run, started voltha, onos and related containers using docker-compose
2. Pushed hsia flows at onos 

The following is observed at the voltha-cli:
(voltha) devices
Devices:
+------------------+-------------------+------+------------------+---------------+-------------+-------------+----------------+----------------+------------------+-----------------------------------------------+-------------------------+--------------------------+----------------------+------------------------------+
|               id |              type | root |        parent_id | serial_number | admin_state | oper_status | connect_status | parent_port_no |    host_and_port |                                        reason | proxy_address.device_id | proxy_address.channel_id | proxy_address.onu_id | proxy_address.onu_session_id |
+------------------+-------------------+------+------------------+---------------+-------------+-------------+----------------+----------------+------------------+-----------------------------------------------+-------------------------+--------------------------+----------------------+------------------------------+
| 0001f0669bd043df |           openolt | True | 000100000a0a0173 |   BBSIMOLT001 |     ENABLED |      ACTIVE |      REACHABLE |                | 10.10.1.115:9191 |                                               |                         |                          |                      |                              |
| 00017c3fd7499106 | brcm_openomci_onu |      | 0001f0669bd043df |  BBSM00010101 |     ENABLED |      ACTIVE |      REACHABLE |      536870913 |                  | **tech-profile-config-download-failure-retrying** |        0001f0669bd043df |                        1 |                    1 |                            1 |
+------------------+-------------------+------+------------------+---------------+-------------+-------------+----------------+----------------+------------------+-----------------------------------------------+-------------------------+--------------------------+----------------------+------------------------------+

The following error is seen in the voltha logs:

`**20190415T074313.622 ERROR    MainThread omci_get_request.perform_get_missing_attributes {'instance_id': 'vcore-594c99c447-78dkc_1555308978', 'entity_id': 32770, 'exception': 'Traceback (most recent call last):\n  File "/voltha/voltha/extensions/omci/tasks/omci_get_request.py", line 276, in perform_get_missing_attributes\n    assert attr_mask == get_omci[\'attributes_mask\'], \'wrong attribute\'\nAssertionError: wrong attribute', 'e': AssertionError('wrong attribute',), 'name': 'ONU OMCI Get Task', 'task_id': 7, 'class_id': 130, 'vcore_id': '0001', 'event': 'missing-failure', 'device_id': '0001f09d83a6944b'}
20190415T074313.622 DEBUG    MainThread task_runner._on_task_failure {'task_id': 'Task: ONU OMCI Get Task, ID:7, Priority: 128, Exclusive: True, Watchdog: 10', 'vcore_id': '0001', 'instance_id': 'vcore-594c99c447-78dkc_1555308978', 'running': 1, 'event': 'task-failure', 'pending': 1, 'device_id': '0001f09d83a6944b'}
20190415T074313.623 WARNING  MainThread mib_sync.failure {'entity_id': 32770, 'class_id': 130, 'vcore_id': '0001', 'instance_id': 'vcore-594c99c447-78dkc_1555308978', 'reason': <twisted.python.failure.Failure exceptions.AssertionError: wrong attribute>, 'attributes': set(['tp_type', 'unmarked_frame_option', 'dscp_to_p_bit_mapping', 'default_p_bit_marking']), 'event': 'update-sbc-w-failed', 'device_id': '0001f09d83a6944b'}
Unhandled error in Deferred:**
20190415T074346.979 DEBUG    MainThread **brcm_tp_service_specific_task.perform_service_specific_steps {'instance_id': 'vcore-594c99c447-78dkc_1555308978', 'vcore_id': '0001', 'uni_id': 0, 'ul_prior_q': {}, 'event': 'ul-prior-q', 'device_id': '0001f09d83a6944b'}
20190415T074346.979 DEBUG    MainThread brcm_tp_service_specific_task.perform_service_specific_steps {'vcore_id': '0001', 'uni_id': 0, 'instance_id': 'vcore-594c99c447-78dkc_1555308978', 'dl_prior_q': {}, 'event': 'dl-prior-q', 'device_id': '0001f09d83a6944b'}**

20190415T074326.861 ERROR    MainThread brcm_tp_service_specific_task.perform_service_specific_steps {'exception': 'Traceback (most recent call last):\n  File "/voltha/voltha/adapters/brcm_openomci_onu/omci/brcm_tp_service_specific_task.py", line 310, in perform_service_specific_steps\n    self.tcont_me_to_queue_map[tcont.entity_id].sort()\nKeyError: 32768', 'e': KeyError(32768,), 'vcore_id': '0001', 'uni_id': 0, 'instance_id': 'vcore-594c99c447-78dkc_1555308978', 'event': 'omci-setup-2', 'device_id': '0001f09d83a6944b'}
20190415T074326.862 DEBUG    MainThread task_runner._on_task_failure {'task_id': 'Task: Broadcom Tech-Profile Download Task, ID:17, Priority: 138, Exclusive: True, Watchdog: 10', 'vcore_id': '0001', 'instance_id': 'vcore-594c99c447-78dkc_1555308978', 'running': 1, 'event': 'task-failure', 'pending': 0, 'device_id': '0001f09d83a6944b'}
20190415T074326.862 WARNING  MainThread brcm_openomci_onu_handler.failure **{'instance_id': 'vcore-594c99c447-78dkc_1555308978', 'vcore_id': '0001', '_reason': <twisted.python.failure.Failure exceptions.KeyError: 32768>, 'event': 'tech-profile-config-failure-retrying', 'device_id': '0001f09d83a6944b'}**
20190415T074326.863 DEBUG    MainThread device_agent.update_device {'device': '0001f09d83a6944b', 'instance_id': 'vcore-594c99c447-78dkc_1555308978', 'vcore_id': '0001', 'event': 'updating-device', 'device_id': '0001f09d83a6944b'}`

Kindly provide your assistance.
Thanks

**Comment by siddiqui-io** [comment]
Resolved
